OS:
  SanitizeA:
    "F38":
      TYPE: scripted
      IMAGE: fedora38
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  SanitizeB:
    "F38":
      TYPE: scripted
      IMAGE: fedora38
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  SanitizeC:
    "F38":
      TYPE: scripted
      IMAGE: fedora38
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
