JENKINS_TESTTYPES:
  - bareos-client-only
  - bareos-postgresql
  - univention-bareos
  - bareos-universal-client

OS:
  EL:
    "8":
      TYPE: rpm
      IMAGE: rocky8
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
  win:
    cross:
      TYPE: win
      STAGES:
        - win-32-release
        - win-64-release
      ARCH:
       - x86_64
      PROJECTPACKAGES:
        x86_64:
           - mingw-debugsrc
           - mingw32-winbareos
           - mingw64-winbareos
           - winbareos-nsi
           - winbareos-opsi
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
