OS:
  Fedora:
    "39":
      TYPE: rpm
      IMAGE: fedora39
      ARCH:
      - x86_64
  win:
    cross:
      TYPE: win
      STAGES:
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-64
