OS:
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: debian9.0
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      ARCH:
        - i586
        - x86_64

  xUbuntu:
    "22.04":
      TYPE: deb
      IMAGE: "ubuntu22.04"
      ARCH:
        - x86_64
    "20.04":
      TYPE: deb
      IMAGE: "ubuntu20.04"
      ARCH:
        - x86_64
    "18.04":
      TYPE: deb
      IMAGE: "ubuntu18.04"
      ARCH:
        - x86_64

  openSUSE:
    "Leap_15.4":
      TYPE: rpm
      IMAGE: opensuse-leap154
      CUSTOM_TEST_IMAGES: [ openSUSE-Leap_15.4 ]
      ARCH:
      - x86_64

  SLE:
    "15_SP4":
      TYPE: rpm
      IMAGE: sle154
      CUSTOM_TEST_IMAGES: [ SLE-15_SP4 ]
      ARCH:
      - x86_64
    "15_SP3":
      TYPE: rpm
      IMAGE: sle153
      CUSTOM_TEST_IMAGES: [ SLE-15_SP4 ]
      ARCH:
      - x86_64
    "15_SP2":
      TYPE: rpm
      IMAGE: sle152
      CUSTOM_TEST_IMAGES: [ SLE-15_SP4 ]
      ARCH:
      - x86_64
    "12_SP5":
      TYPE: rpm
      IMAGE: sles12sp5
      ARCH:
      - x86_64

  RHEL:
    "8":
      TYPE: rpm
      IMAGE: rhel8
      ARCH:
      - x86_64
    "7":
      TYPE: rpm
      IMAGE: rhel7
      ARCH:
      - x86_64

  Fedora:
    "36":
      TYPE: rpm
      IMAGE: fedora36
      ARCH:
      - x86_64
  Debian:
    "11":
      TYPE: deb
      IMAGE: "debian11"
      ARCH:
        - x86_64
    "10":
      TYPE: deb
      IMAGE: "debian10"
      ARCH:
        - x86_64
  EL:
    "9":
      TYPE: rpm
      IMAGE: centos9
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream ]
      ARCH:
      - x86_64
    "8":
      TYPE: rpm
      IMAGE: rocky8
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream ]
      ARCH:
      - x86_64
  CentOS:
    "7":
      TYPE: rpm
      IMAGE: centos7
      ARCH:
      - x86_64
  FreeBSD:
    "12.4":
      TYPE: freebsd
      ARCH:
        - amd64
    "13.1":
      TYPE: freebsd
      ARCH:
        - amd64
  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64
  win:
    cross:
      TYPE: win
      STAGES:
        - win-32-release
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
