JENKINS_TESTTYPES:
  - bareos-client-only+bareos-universal-client+bareos-postgresql
  - univention-bareos

OS:
  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64
      PROJECTPACKAGES:
        x64:
