name: Report a Bug
description: |
  You found a bug in Bareos causing the application to crash or
  throw an exception, a component is buggy, or something looks wrong.
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Bareos and taking the time to fill out this bug report!

        If you are looking for support, please check out our documentation or consider asking a question on mailing list:

          - https://doc.bareos.org/
          - https://groups.google.com/u/1/g/bareos-users
  - type: markdown
    attributes:
      value: |
        Before filling the form fields, please consider the following:
        - Ensure that you have searched the [existing issues](https://github.com/bareos/bareos/issues)
        - Read the [troubleshooting guide](https://docs.bareos.org/Appendix/Troubleshooting.html)
        - Read the [guide to filing a bug](https://docs.bareos.org/Appendix/Troubleshooting.html#bug-reports)

        **What is a bug?** A bug describes an unexpected trouble with the software which
        proves a divergence with the documentation, and/or a crash (trace) that are
        somewhat reproducible.

        We recommend to discuss your issue on the [mailing list](https://groups.google.com/u/1/g/bareos-users) first.
  - type: textarea
    id: bareos_version
    attributes:
      label: Bareos component version
      description: Please fill the version of each Bareos component you are seeing the problem on
      placeholder: |
        1. bareos-fd --version
        2. bareos-dir --version
        3. bareos-sd --version
        4. bconsole --version
        5. ... `any plugins installed`
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem you are running into.
      placeholder: |
        1. ...
        2. ...

        Note: Please try to ensure the bug is reproducible on another system!

    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected results
      description: Please tell us what is expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual results
      description: Please tell us what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: _`cat /etc/os-release`_
          - **component**: precise plugin or tools for example, specific filesystem, etc.
      value: |
          - OS: ``
          - component:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Relevant log output
      description: |
        Please include any logs or command output, they will be automatically formatted into code, so no need for backticks. If you are running any `bareos` commands, please include the output of running them with `-d 250 --dt`. For example, the output of running `bconsole -d200 --dt | tee -a /var/tmp/bconsole_debug.log`.

        If the logs are too large to be uploaded to GitHub, you may upload them as a `txt` file or use online tools like https://pastebin.com to share them.

        Note: Please do not upload screenshots of text. Instead, use code blocks or the above mentioned ways to upload logs.
      render: shell
  - type: textarea
    id: trace
    attributes:
      label: Relevant traces output
      description: |
        Include the full trace files you will find in your working directory `/var/lib/bareos`.

        While running you may want to increase the debug level of daemon you can refer to [how to setdebug level](https://docs.bareos.org/TasksAndConcepts/BareosConsole.html#bcommandsetdebug)
        If the logs are too large to be uploaded to GitHub, you may upload them as a `txt` file or use online tools like https://pastebin.com to share them.

        Note: Please do not upload screenshots of text. Instead, use code blocks or the above mentioned ways to upload traces.
      render: shell
  - type: textarea
    id: supplements
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
